### ISSUE TITLE
Correct no of arguments in ask call, but get java.lang.RuntimeException: end of structure expected found

### ISSUE THREAD

**Issue by davidwynter** [RuedigerMoeller/kontraktor#42] opened 2017-06-08 15:43 UTC
I have this test case, the part giving errors is:

                    	var anAddr = jsk.jobj(
                    			"example.Address",
                                {
                                	addr1: "232",
                                	addr2: "High Street",
                                 }
                    	)
                    	var addrList = jsk.buildJColl("list", [anAddr]);
                    	
                    	session.ask(
                            "identity",
                            "heidi.popplewell@yahoo.com",
                            "1nyqs6",
                            addrList,
                            "device1",
                            "device2",
                            "HO",
                        	16500000, 
                        	"EMPLOYED", 
                        	36,
                        	3500000, 
                        	2000000, 
				"HSBC"
                        ).then((sess, err) => {
                            console.log(sess);
                            console.log(err);
                        })

The Promise call is 

	public IPromise<InteractiveQuery> identity(String username, String password, 
			List<cs.dmn.Address> addresses, String device1, String device2, String residentialStatus,
			int propertyValue, String employStatus, int employDuration, int grossIncome, 
			int usersIncome, String bankWith) {

The error I get is:

    unable to decode:{"styp":"array","seq":[12,"heidi.popplewell@yahoo.com","1nyqs6",{"typ":"list","obj":[1,{"typ":"uk.co
    E 16:34:01:503 : XNIO-1 I/O-7 :  : null
    java.io.IOException: java.lang.RuntimeException: end of structure expected found:VALUE_STRING : value:HSBC fname:'null'
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:243)
	at org.nustaq.serialization.FSTConfiguration.asObject(FSTConfiguration.java:1107)
	at org.nustaq.kontraktor.remoting.encoding.RemoteCallEntry.unpackArgs(RemoteCallEntry.java:138)
	at org.nustaq.kontraktor.Actor.__dispatchRemoteCall(Actor.java:622)
	at org.nustaq.kontraktor.remoting.base.RemoteRegistry.processRemoteCallEntry(RemoteRegistry.java:344)
	at org.nustaq.kontraktor.remoting.base.RemoteRegistry.receiveObject(RemoteRegistry.java:303)
	at org.nustaq.kontraktor.remoting.base.ActorServer$3.receiveObject(ActorServer.java:107)
	at org.nustaq.kontraktor.remoting.base.ObjectSink.receiveObject(ObjectSink.java:38)
	at org.nustaq.kontraktor.remoting.websockets.UndertowWebsocketServerConnector$1.onFullTextMessage(UndertowWebsocketServerConnector.java:99)
	at io.undertow.websockets.core.AbstractReceiveListener$2.complete(AbstractReceiveListener.java:156)
	at io.undertow.websockets.core.AbstractReceiveListener$2.complete(AbstractReceiveListener.java:152)
	at io.undertow.websockets.core.BufferedTextMessage.read(BufferedTextMessage.java:105)
	at io.undertow.websockets.core.AbstractReceiveListener.readBufferedText(AbstractReceiveListener.java:152)
	at io.undertow.websockets.core.AbstractReceiveListener.bufferFullMessage(AbstractReceiveListener.java:90)
	at io.undertow.websockets.core.AbstractReceiveListener.onText(AbstractReceiveListener.java:70)
	at io.undertow.websockets.core.AbstractReceiveListener.handleEvent(AbstractReceiveListener.java:44)
	at io.undertow.websockets.core.AbstractReceiveListener.handleEvent(AbstractReceiveListener.java:33)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:775)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:763)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:539)
    Caused by: java.lang.RuntimeException: end of structure expected found:VALUE_STRING : value:HSBC fname:'null'
	at org.nustaq.serialization.coders.FSTJsonDecoder.consumeEnd(FSTJsonDecoder.java:602)
	at org.nustaq.serialization.coders.FSTJsonDecoder.readObjectEnd(FSTJsonDecoder.java:626)
	at org.nustaq.serialization.FSTObjectInput.readArrayNoHeader(FSTObjectInput.java:901)
	at org.nustaq.serialization.FSTObjectInput.readArray(FSTObjectInput.java:877)
	at org.nustaq.serialization.FSTObjectInput.instantiateArray(FSTObjectInput.java:456)
	at org.nustaq.serialization.FSTObjectInput.instantiateSpecialTag(FSTObjectInput.java:425)
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:360)
	at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:327)
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:298)
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:241)
	... 23 more

The correct number of args is there. Maybe it is the way I setup the addList collection, no examples of how to do this that I could find.

Ideas?

**Comment by RuedigerMoeller** [comment] 2017-06-08 15:48
will have to reproduce first .. can you provide the corresponding java class ?

**Comment by davidwynter** [comment] 2017-06-08 16:04
Just slip this into the example MyHttpApp.java in the example app:

    public IPromise<String> identity(String username, String password, 
		List<example.Address> addresses, String device1, String device2, String residentialStatus,
		int propertyValue, String employStatus, int employDuration, int grossIncome, 
		int usersIncome, String bankWith) {
                return username + " " + surname + " " + addresses.get(0).addr1;
        }

example.Address can just be

    package example
    public class Address implements Serializable {
        public String addr1 = "";
        public String addr2 = "";
    }

**Comment by RuedigerMoeller** [comment] 2017-06-08 16:05
ok thanks, will have a look into it tomorrow ..

**Comment by RuedigerMoeller** [comment] 2017-06-09 12:17
I tried it with a freshly setup MyHttpApp.java and the call works fine (the test calls are checked in, so you might want to verify this yourself).

![image](https://user-images.githubusercontent.com/6097932/26975025-5a616e90-4d1e-11e7-9516-53f8c6e5b2b5.png)

probably the issues is caused by using a different version of jackson ?

**Comment by RuedigerMoeller** [comment] 2017-06-19 11:39
hi, any news on this ? Did it work by downgrading jackson or do you still have this error ?

**Comment by davidwynter** [comment] 2017-06-20 12:58
I had 3 address classes used for different purposes, the wrong one was specified in the remote call. So this problem was unrelated to the version of FST. 

I'll try a branch of Kontraktor 3.33 with FST 2.44.5 using the latest Jackson 2.8.2. But not this week, too busy.

**Comment by RuedigerMoeller** [comment] 2017-06-20 14:06
fine :)

**Closed as completed by RuedigerMoeller** 2017-06-20 14:06 UTC
